#!/bin/bash
# Post-install script V3: The Skel Injector

echo "🎨 Memulai Operasi Plastik V3 (Skel Injection)..."

# 1. Identitas OS Release
cat <<EOF > /etc/os-release
PRETTY_NAME="Nusa OS V1 Alpha"
NAME="Nusa OS"
VERSION_ID="1.0"
VERSION="1.0 Alpha (Z-Core DNA)"
VERSION_CODENAME=alpha
ID=nusa
ID_LIKE=ubuntu
HOME_URL="https://github.com/Nusa-OS"
EOF

# 2. Bunuh Hostname Ubuntu dari Casper (Pake metode Append biar tembus)
echo 'export HOSTNAME="nusa-os"' >> /etc/casper.conf
echo 'export FLAVOUR="Nusa OS"' >> /etc/casper.conf
echo 'export USERNAME="nusa"' >> /etc/casper.conf
echo 'export USERFULLNAME="Nusa OS Live"' >> /etc/casper.conf

echo "nusa-os" > /etc/hostname
echo "127.0.0.1 localhost" > /etc/hosts
echo "127.0.1.1 nusa-os" >> /etc/hosts

# 3. HACK WALLPAPER XFCE VIA /etc/skel/ (Ini kunciannya!)
mkdir -p /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/
cat <<EOF > /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
<?xml version="1.0" encoding="UTF-8"?>
<channel name="xfce4-desktop" version="1.0">
  <property name="backdrop" type="empty">
    <property name="screen0" type="empty">
      <property name="monitor0" type="empty">
        <property name="workspace0" type="empty">
          <property name="last-image" type="string" value="/usr/share/backgrounds/nusa/default.jpg"/>
        </property>
      </property>
    </property>
  </property>
</channel>
EOF

# 4. HACK LIGHTDM (Lockscreen) & Hapus Cache Debian
cat <<EOF > /etc/lightdm/lightdm-gtk-greeter.conf
[greeter]
background=/usr/share/backgrounds/nusa/default.jpg
theme-name=Adwaita
icon-theme-name=Adwaita
font-name=Sans 11
EOF

rm -f /usr/share/images/desktop-base/default
ln -s /usr/share/backgrounds/nusa/default.jpg /usr/share/images/desktop-base/default

echo "✅ Identitas Nusa OS V3 berhasil dipasang di akar skel!"
exit 0
