#!/bin/bash

echo "🎨 Memulai Operasi Plastik Nusa OS..."

# 1. Ganti Identitas Sistem (OS Release)
cat <<EOF > /etc/os-release
PRETTY_NAME="Nusa OS V1 Alpha"
NAME="Nusa OS"
VERSION_ID="1.0"
VERSION="1.0 Alpha (Z-Core DNA)"
VERSION_CODENAME=alpha
ID=nusa
ID_LIKE=ubuntu
HOME_URL="https://github.com/Nusa-OS"
EOF

# 2. Membunuh Hostname 'Ubuntu' dari Live CD (Casper)
if [ -f /etc/casper.conf ]; then
    sed -i 's/export HOSTNAME=.*/export HOSTNAME="nusa-os"/' /etc/casper.conf
    sed -i 's/export FLAVOUR=.*/export FLAVOUR="Nusa OS"/' /etc/casper.conf
fi
echo "nusa-os" > /etc/hostname
sed -i 's/ubuntu/nusa-os/g' /etc/hosts

# 3. Paksa Konfigurasi LightDM (Lockscreen)
cat <<EOF > /etc/lightdm/lightdm-gtk-greeter.conf
[greeter]
background=/usr/share/backgrounds/nusa/default.jpg
theme-name=Adwaita
icon-theme-name=Adwaita
font-name=Sans 11
EOF

# 4. Brutal Force Wallpaper XFCE & Debian
# XFCE default config override
mkdir -p /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/
cat <<EOF > /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
<?xml version="1.0" encoding="UTF-8"?>
<channel name="xfce4-desktop" version="1.0">
  <property name="backdrop" type="empty">
    <property name="screen0" type="empty">
      <property name="monitor0" type="empty">
        <property name="workspace0" type="empty">
          <property name="last-image" type="string" value="/usr/share/backgrounds/nusa/default.jpg"/>
        </property>
      </property>
    </property>
  </property>
</channel>
EOF


cp -f /usr/share/backgrounds/nusa/default.jpg /usr/share/images/desktop-base/default || true

echo "✅ Identitas Nusa OS V2 berhasil dipasang!"
exit 0
